/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package minispiele_Tetris;

import java.awt.Component;
import javax.swing.JLayeredPane;
import static minispiele_PingPong.PingPong.HEIGHT_FIELD;
import static minispiele_PingPong.PingPong.WIDTH_FIELD;

/**
 *
 * @author mtukendo
 */
public class TetrisFrame extends javax.swing.JFrame {

    private Component comp;

    /**
     * Creates new form TetrisFrame
     */
    public TetrisFrame(Component compo) {
        initComponents();
        this.comp = compo;        
        comp.setBounds(0, 0, WIDTH_FIELD, HEIGHT_FIELD);
        //layers.add(comp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 659));
        //layers.setLayer(comp, JLayeredPane.MODAL_LAYER);
        add(comp);
        setVisible(true);
        setLocationRelativeTo(null);
        setResizable(false);
        setDefaultCloseOperation(HIDE_ON_CLOSE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layers = new javax.swing.JLayeredPane();
        jLabelBeenden = new javax.swing.JLabel();
        jLabelNeuesSpiel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        layers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelBeenden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tetris_img/Botton_end.jpg"))); // NOI18N
        jLabelBeenden.setText("jLabel3");
        jLabelBeenden.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelBeendenMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelBeendenMouseReleased(evt);
            }
        });

        jLabelNeuesSpiel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tetris_img/Botton_neuesSpiel.jpg"))); // NOI18N
        jLabelNeuesSpiel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelNeuesSpielMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelNeuesSpielMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(430, 430, 430)
                .addComponent(jLabelNeuesSpiel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabelBeenden, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(layers, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layers, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(590, 590, 590)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNeuesSpiel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBeenden, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelBeendenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBeendenMousePressed
        jLabelBeenden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tetris_img/Botton_Beenden.jpg")));
    }//GEN-LAST:event_jLabelBeendenMousePressed

    private void jLabelBeendenMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBeendenMouseReleased
        jLabelBeenden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tetris_img/Botton_end.jpg")));
        setVisible(false);
    }//GEN-LAST:event_jLabelBeendenMouseReleased

    private void jLabelNeuesSpielMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNeuesSpielMousePressed
        jLabelNeuesSpiel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tetris_img/Botton_neuesSpiel_pressed.jpg")));
    }//GEN-LAST:event_jLabelNeuesSpielMousePressed

    private void jLabelNeuesSpielMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNeuesSpielMouseReleased
       jLabelNeuesSpiel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tetris_img/Botton_neuesSpiel.jpg")));
       Tetris t = new Tetris();
       //comp = t;
       setVisible(false);
    }//GEN-LAST:event_jLabelNeuesSpielMouseReleased

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelBeenden;
    private javax.swing.JLabel jLabelNeuesSpiel;
    private javax.swing.JLayeredPane layers;
    // End of variables declaration//GEN-END:variables
}
